tap "adoptopenjdk/openjdk"
tap "argon/mas"
tap "charmbracelet/tap"
tap "cuelang/tap"
tap "dandavison/delta", "https://github.com/dandavison/delta"
tap "elastic/tap"
tap "github/bootstrap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/portable"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "kyoh86/tap"
tap "loadimpact/k6"
tap "nektos/tap"
tap "neovim/neovim"
tap "rbenv/tap"
tap "shopify/shopify"
tap "skeema/tap"
brew "adr-tools"
brew "openssl@1.1"
brew "apr-util"
brew "gdbm"
brew "readline"
brew "asciinema"
brew "aspell"
brew "autoconf"
brew "automake"
brew "aws-iam-authenticator"
brew "awscli"
brew "python@3.8"
brew "azure-cli"
brew "bash"
brew "bat"
brew "bison"
brew "libffi"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "certstrap"
brew "chruby"
brew "cmake"
brew "cocoapods"
brew "container-diff"
brew "coreutils", link: false
brew "jemalloc"
brew "libev"
brew "libssh2"
brew "curl"
brew "docker", link: false
brew "libyaml"
brew "docker-compose", link: false
brew "openjdk"
brew "elasticsearch", link: false
brew "exercism"
brew "gnutls"
brew "icu4c"
brew "harfbuzz"
brew "jpeg"
brew "webp"
brew "libsodium"
brew "snappy"
brew "ffmpeg"
brew "filebeat", restart_service: true
brew "fswatch"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "go"
brew "glide"
brew "libusb"
brew "gnupg"
brew "golang-migrate"
brew "pango"
brew "graphviz"
brew "hivemind"
brew "htmldoc"
brew "hub"
brew "hugo"
brew "hyperscan"
brew "libheif"
brew "imagemagick"
brew "ios-webkit-debug-proxy"
brew "jansson"
brew "jq"
brew "zookeeper"
brew "kafka"
brew "kibana", restart_service: true
brew "krb5"
brew "kubernetes-cli"
brew "launch_socket_server"
brew "launchdns", restart_service: true
brew "lcov"
brew "lftp"
brew "libgee"
brew "libgda"
brew "librdkafka"
brew "libxml2"
brew "lua"
brew "lynx"
brew "mackup"
brew "mas"
brew "maven"
brew "md5sha1sum", link: false
brew "memcached", restart_service: true
brew "mercurial"
brew "minikube"
brew "mkcert"
brew "mono-libgdiplus"
brew "vapoursynth"
brew "youtube-dl"
brew "mpv"
brew "mysql-client"
brew "mysql@5.7", restart_service: true
brew "ncurses"
brew "neovim"
brew "nginx", restart_service: true
brew "node"
brew "node-build"
brew "nodenv"
brew "nss"
brew "openjdk@11"
brew "openvpn"
brew "tmux"
brew "overmind"
brew "p7zip"
brew "pandoc"
brew "perl"
brew "pidof"
brew "pinentry-mac"
brew "protobuf"
brew "pyenv"
brew "qt"
brew "rakudo-star"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "ruby-install"
brew "rust"
brew "sbt"
brew "shellcheck"
brew "sl"
brew "socat"
brew "softhsm"
brew "ssdeep"
brew "subversion"
brew "terminal-notifier"
brew "terraform"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tldr"
brew "tree"
brew "v8"
brew "vale"
brew "watchman"
brew "wget"
brew "yarn"
brew "ydiff"
brew "zsh"
brew "charmbracelet/tap/glow"
brew "cuelang/tap/cue"
brew "github/bootstrap/elasticsearch@2.4"
brew "heroku/brew/heroku"
brew "kyoh86/tap/richgo"
brew "loadimpact/k6/k6"
brew "nektos/tap/act"
brew "rbenv/tap/openssl@1.0"
brew "shopify/shopify/secret-sender"
brew "skeema/tap/skeema"
cask "1password"
cask "1password-cli"
cask "adoptopenjdk"
cask "alfred"
cask "anaconda"
cask "calibre"
cask "chromedriver"
cask "dash"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "flux"
cask "insomnia"
cask "iterm2"
cask "mactex"
cask "moonlight"
cask "ngrok"
cask "notion"
cask "phantomjs"
cask "postgres"
cask "sequel-pro"
cask "sketch"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "viscosity"
cask "visual-studio-code"
cask "whatsapp"
cask "wireshark"
cask "wkhtmltopdf"
cask "zoom"
mas "Base", id: 402383384
mas "Dato", id: 1470584107
mas "GIF Brewery 3", id: 1081413713
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Moom", id: 419330170
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
