#!/bin/ruby

branch = ARGV[0]
repo = ARGV[1]

if branch.include?(':')
  user, branch_name = branch.split(':')
  user.strip!
  branch_name.strip!

  unless`git remote`.include?(user)
    cmd = "git remote add #{user} https://github.com/#{user}/#{repo.downcase}.git"
    system(cmd)
  end
  system("git fetch #{user}")
  system("git checkout #{user}/#{branch_name}")
else
  system("git fetch origin")
  system("git checkout origin/#{branch}")
end
