export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME="/usr/local/opt/android-sdk"
export GOPATH="$HOME"
export EDITOR="vi"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_BUNDLE_BREW_SKIP=1
export GITHUB_PROFILE_BOOTSTRAP=1
export GITHUB_NO_AUTO_BOOTSTRAP=1

export PATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
export PATH="/user/local:$PATH"
export PATH="/usr/local/git/bin:$PATH"
export PATH="~/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:$GOPATH/bin"
export PATH="$HOME/dotfiles/scripts/:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:/usr/local/opt/mysql@5.7/bin"
export PATH="$(brew --prefix qt)/bin:$PATH"
export PATH="$PATH:/Users/juliannadeau/src/github.com/github/gh-helper-cli/exe"